### ISSUE TITLE
Add elements to the canvas

### ISSUE THREAD

**Issue by BlackRam-oss** [DRincs-Productions/pixi-vn-ink#24]
adding a syntax to handle the canvas is not easy.
the following points should be handled:
- add (even with transitions) an element by assigning an id
- remove an element by id
- edit an element by id
- run Animations and Effects

my idea is that :

To add (even with transitions) an element by assigning an id, you should write `show` + Canvas element + id + url + (optional) transition type + (optional) transitions props:

```ink
#show image bg /image.png
#show image "bg 2" /image2.png
#show image bg /image.png dissolve
#show image bg /image.png dissolve duration 3
Hello
```

To edit, you should write `edit` + id + props:

```ink
#edit image bg x 20 y 30
Hello
```

To remove, you should write `remove` + id

```ink
#remove image bg
#remove image "bg 2"
#remove image bg dissolve
#remove image bg dissolve duration 3
Hello
```

To run Animations and Effects, you should name of Animations or Effects + id + props

```ink
#move image bg x 20 y 40
Hello
```
can do the same for videos, but also add:

- play
- pause
- resume
- stop

**Comment by blurymind** [comment]
potentially, if you have an interface similar to renpy - where you can trigger a command with parameters - to show a character avatar on the left or the right, changing its emotes and so on - this can be interfaced via both ink and yarn with some bridge logic.

This is kind of how it already works in Gdevelop. The wrapper I made there can intercept yarn's `<<command param1 param2>> `calls and you can setup in the event sheet what they do in the game logic.

I think doing it with ink is exactly the same or similar. You can have the inkjs parser detect when a `//command param1 param2` is hit and have that trigger calls to inkvn to draw a sprite for example. It can literally be a 1:1 what you write in yarn/inkjs and what is called in pixivn.

You still need a basic bridge to link one interface to the other of course, unless inkjs is not entirely parsed by pixivn.

Allowing pixivn's interface to directly have commands to show sprites and play sounds and so on would empower it being used with any other system - not just yarn or ink :)

**Comment by BlackRam-oss** [comment]
is it possible to create a bridge that parses ink events???

I am currently parsing the entire array generated by the ink paraser, in order to create a json in "PixiVNJson" format that is read by pixi-vn.
the same implementation will also be done for renpy, and other narrative languages.

Can the syntax I wrote be fine like this or could it be improved?

**Comment by BlackRam-oss** [comment]
> potentially, if you have an interface similar to renpy - where you can trigger a command with parameters - to show a character avatar on the left or the right, changing its emotes and so on - this can be interfaced via both ink and yarn with some bridge logic.

Here is the full list of interactions between pixi-vn and ink: https://github.com/DRincs-Productions/pixi-vn-ink/issues/26#issue-2466753128
